services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mibasededatos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install --prefer-offline --no-audit && npm start"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mibasededatos
      DB_USER: postgres
      DB_PASSWORD: password123
      PORT: 3000
    depends_on:
      - db

volumes:
  db_data: